{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ .Release.Name }}"
  labels:
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: aws-exporter
  endpoints:
  - port: aws
    path: /aws-exporter/actuator/prometheus
  - port: jmx
{{- end }}